config/routes.rb
Corpservice::Application.routes.draw do
  
  resources :workorders
  resources :clients do
    resources :locations do
      resources :franchises do
        resources :workorders do
        end
      end
    end
  end
  root 'clients#index'

end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :locations, :dependent => :destroy
  accepts_nested_attributes_for :locations, :allow_destroy => :true
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all.order('account')
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
    @clients = Client.find(params[:id])
    @locations = @client.locations
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render action: 'show', status: :created, location: @client }
      else
        format.html { render action: 'new' }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:account, :contact, :phone, :email)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= form_for(@client) do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% @client.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :account %><br>
    <%= f.text_field :account, :style => "width: 600px;" %>
  </div>
  <div class="field">
    <%= f.label :contact %><br>
    <%= f.text_field :contact, :style => "width: 600px;" %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone, :style => "width: 600px;" %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email, :style => "width: 600px;" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing client</h1>

<%= render 'form' %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<h1>Listing Clients</h1>

<table>
  <thead>
    <tr>
      <th>Account</th>
      <th>Contact</th>
      <th>Phone</th>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.account %></td>
        <td><%= client.contact %></td>
        <td><%= client.phone %></td>
        <td><%= client.email %></td>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form' %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Account:</strong>
  <%= @client.account %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @client.contact %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @client.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @client.email %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %> |
<%= link_to 'Add Location', new_client_location_path(@client) %>

<h1>Listing Locations</h1>

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Address1</th>
      <th>Address2</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th>Phone</th>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @client.locations.each do |location| %>
      <tr>
        <td><%= location.code %></td>
        <td><%= location.address1 %></td>
        <td><%= location.address2 %></td>
        <td><%= location.city %></td>
        <td><%= location.state %></td>
        <td><%= location.zip %></td>
        <td><%= location.phone %></td>
        <td><%= location.email %></td>

        <td><%= link_to 'Show', client_location_path(@client, location) %></td>
        <td><%= link_to 'Edit', edit_client_location_path(@client, location) %></td>
        <td><%= link_to 'Destroy', [@client, location], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Location', new_client_location_path(@client) %>