config/routes.rb
Corpservice::Application.routes.draw do
  
  resources :workorders
  resources :clients do
    resources :locations do
      resources :franchises do
        resources :workorders do
        end
      end
    end
  end
  root 'clients#index'

end

app/controllers/franchises_controller.rb
class FranchisesController < ApplicationController
  before_action  :set_franchise, only: [:show, :edit, :update, :destroy]
before_action :load_client, :load_location, only: [:new, :create, :show, :index, :edit,:destroy, :update]

  # GET /franchises
  # GET /franchises.json
  def index
    @franchises = @location.franchises.order(:name)
    #@franchises = Franchise.all
  end

  # GET /franchises/1
  # GET /franchises/1.json
  def show
    @franchise = Franchise.find(params[:id])
  end

  # GET /franchises/new
  def new
    @franchise = @location.franchises.new
  end

  # GET /franchises/1/edit
  def edit
    
  end

  # POST /franchises
  # POST /franchises.json
  def create
    @franchise = @location.franchises.new(franchise_params)

    respond_to do |format|
      if @franchise.save
        format.html { redirect_to [@client, @location, @franchise], notice: 'Franchise was successfully created.' }
        format.json { render action: 'show', status: :created, location: @franchise }
      else
        format.html { render action: 'new' }
        format.json { render json: @franchise.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /franchises/1
  # PATCH/PUT /franchises/1.json
  def update
    respond_to do |format|
      if @franchise.update(franchise_params)
        format.html { redirect_to [@client, @location, @franchise], notice: 'Franchise was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @franchise.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /franchises/1
  # DELETE /franchises/1.json
  def destroy
    @franchise.destroy
    respond_to do |format|
      format.html { redirect_to client_location_franchises_path(@client, @location) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_franchise
      @franchise = Franchise.find(params[:id])
    end

    def load_client
      @client = Client.find(params[:client_id])
    end

    def load_location
      @location = Location.find(params[:location_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def franchise_params
      params.require(:franchise).permit(:number, :name, :phone, :email, :location_id, 
          location: [:id, :code, :address1, :address2, :city, :state, :zip, :phone, :email, :client_id])
    end
end

app/helpers/franchises_helper.rb
module FranchisesHelper
end

app/views/franchises/_form.html.erb
<%= form_for([@client, @location, @franchise]) do |f| %>
  <% if @franchise.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@franchise.errors.count, "error") %> prohibited this franchise from being saved:</h2>

      <ul>
      <% @franchise.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br>
    <%= f.text_field :number, :style => "width: 600px;" %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, :style => "width: 600px;" %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone, :style => "width: 600px;" %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email, :style => "width: 600px;" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/franchises/edit.html.erb
<h1>Editing franchise</h1>

<%= render 'form' %>

<%= link_to 'Show', client_location_franchise_path(@client, @location, @franchise) %> |
<%= link_to 'Back', client_location_franchises_path(@client,@location ) %>

app/views/franchises/index.html.erb
<h1>Listing Franchises</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Name</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Location</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @franchises.each do |franchise| %>
      <tr>
        <td><%= franchise.number %></td>
        <td><%= franchise.name %></td>
        <td><%= franchise.phone %></td>
        <td><%= franchise.email %></td>
        <td><%= franchise.location_id %></td>
        <td><%= link_to 'Show', client_location_franchise_path(@client, @location, franchise) %></td>
        <td><%= link_to 'Edit', edit_client_location_franchise_path(@client, @location, franchise) %></td>
        <td><%= link_to 'Destroy', [@client, @location, franchise], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Franchise', new_client_location_franchise_path(@client, @location) %>

app/views/franchises/new.html.erb
<h1>New Franchise</h1>

<%= render 'form' %>

<%= link_to 'Back', client_location_franchises_path(@client, @location) %>

app/views/franchises/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @franchise.number %>
</p>

<p>
  <strong>Name:</strong>
  <%= @franchise.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @franchise.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @franchise.email %>
</p>

<p>
  <strong>Location:</strong>
  <%= @franchise.location_id %>
</p>

<%= link_to 'Edit', edit_client_location_franchise_path(@client, @location, @franchise) %> |
<%= link_to 'Back', client_location_franchises_path(@client, @location) %> |
<%= link_to 'Add Workorder', new_client_location_franchise_workorder_path(@client,@location, @franchise) %>


<h1>Listing Workorders</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Po</th>
      <th>Estimate</th>
      <th>Line item</th>
      <th>Quantity</th>
      <th>Price</th>
      <th>Previous action</th>
      <th>Next action due</th>
      <th>Schedule</th>
      <th>Invoice</th>
      <th>Invoice total</th>
      <th>Notes</th>
      <th>Franchises</th>
      <th>Locations</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @franchise.workorders.each do |workorder| %>
      <tr>
        <td><%= workorder.number %></td>
        <td><%= workorder.po %></td>
        <td><%= workorder.estimate_id %></td>
        <td><%= workorder.line_item %></td>
        <td><%= workorder.quantity %></td>
        <td><%= workorder.price %></td>
        <td><%= workorder.previous_action %></td>
        <td><%= workorder.next_action_due %></td>
        <td><%= workorder.schedule %></td>
        <td><%= workorder.invoice %></td>
        <td><%= workorder.invoice_total %></td>
        <td><%= workorder.notes %></td>
        <td><%= link_to 'Show', [@client,@location, @franchise,workorder] %></td>
        <td><%= link_to 'Edit', edit_client_location_franchise_workorder_path(@client,@location, @franchise,workorder) %></td>
        <td><%= link_to 'Destroy', [@client,@location, @franchise,workorder], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Workorder', new_client_workorders_path(@client) %>